export const BASE_URL= 'http://localhost:3001/' //developement
/* export const BASE_URL=  deploy*/
export const PORTFOLIO= 'portfolio'
export const WORK= 'work'
export const TEXT= 'text'
export const BIO= 'bio'
export const COVER= 'cover'
export const EXHIBITIONS= 'exhibitions'
export const WORKS= 'works'
export const CONTACT= 'contact'
