import "../../styles/globals.css";
import { useLocale } from "next-intl";
import Navigation from "./components/Navigation/Navigation";
import SessionProviders from "../sessionProvider";

export const metadata = {
  title: "Maria Ferrari Hardoy- Artista Visual",
  description: "Generated by Next.js",
};

export default function RootLayout({ children, params }) {
  const locale = useLocale();

  if (params.locale !== locale) {
    notFound();
  }

  return (
    <html lang='en'>
      <head>
        <title>Maria Ferrari Hardoy- Artista Visual</title>
      </head>

      <body>
        <header>
          <Navigation />
        </header>
        <SessionProviders>{children}</SessionProviders>
      </body>
    </html>
  );
}
